# Phase 8: AI Zone Clustering

This notebook creates AI-generated valuation zones from the engineered spatial and pricing dataset.

In [1]:
from pathlib import Path
import json
import sys

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'src').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.src.config import configure_logging, ensure_directories, settings
from backend.src.zone_clustering import create_ai_zones, save_zone_outputs

configure_logging()
ensure_directories()
PROJECT_ROOT

WindowsPath('//wsl.localhost/Ubuntu/home/pulkitv52/valuation_poc')

In [2]:
import geopandas as gpd

training_gdf = gpd.read_parquet(settings.processed_data_dir / 'model_training_dataset.parquet')
training_gdf.shape

(273587, 80)

In [3]:
artifacts = create_ai_zones(training_gdf)
artifacts.summary

c:\Users\pulkit verma\miniconda3\envs\xcel\lib\site-packages\threadpoolctl.py:1226: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

ZoneClusteringSummary(input_row_count=273587, rows_with_geometry=207442, rows_used_for_clustering=207442, projected_crs='{"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "WGS 84 / UTM zone 45N", "base_crs": {"type": "GeographicCRS", "name": "WGS 84", "datum_ensemble": {"name": "World Geodetic System 1984 ensemble", "members": [{"name": "World Geodetic System 1984 (Transit)"}, {"name": "World Geodetic System 1984 (G730)"}, {"name": "World Geodetic System 1984 (G873)"}, {"name": "World Geodetic System 1984 (G1150)"}, {"name": "World Geodetic System 1984 (G1674)"}, {"name": "World Geodetic System 1984 (G1762)"}, {"name": "World Geodetic System 1984 (G2139)"}, {"name": "World Geodetic System 1984 (G2296)"}], "ellipsoid": {"name": "WGS 84", "semi_major_axis": 6378137, "inverse_flattening": 298.257223563}, "accuracy": "2.0", "id": {"authority": "EPSG", "code": 6326}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4326}}, "conversion": {"name": "UTM zone 45N", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 87, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Navigation and medium accuracy spatial referencing.", "area": "Between 84\\u00b0E and 90\\u00b0E, northern hemisphere between equator and 84\\u00b0N, onshore and offshore. Bangladesh. Bhutan. China. India. Kazakhstan. Mongolia. Nepal. Russian Federation.", "bbox": {"south_latitude": 0, "west_longitude": 84, "north_latitude": 84, "east_longitude": 90}, "id": {"authority": "EPSG", "code": 32645}}', selected_cluster_count=6, candidate_cluster_range=[6, 7, 8, 9, 10, 11, 12], silhouette_score=0.40787896053474826, feature_columns=['centroid_x', 'centroid_y', 'log_value_per_area', 'log_distance_to_nearest_road', 'log_distance_to_nearest_facility', 'facility_count_1km', 'nearest_road_width', 'Urban_flag', 'Rural_flag', 'flat_flag', 'nature_land_use_freq', 'proposed_land_use_freq', 'nearest_road_category_freq'], output_assignment_rows=207442, output_zone_rows=6)

In [4]:
artifacts.zone_summary_df

,ai_zone,property_count,avg_value_per_area,median_value_per_area,avg_market_value,median_market_value,avg_distance_to_nearest_road,avg_distance_to_nearest_facility,avg_facility_count_1km,avg_nearest_road_width,urban_share,rural_share,flat_share,dominant_district,dominant_mouza,dominant_transaction_type,dominant_land_use,dominant_existing_zone_no
0,AI_ZONE_01,36358,681065.8233,533333.18764,1733229.372078,798001.0,25.553231,363.979546,13.367292,2.987967,0.999917,0.000083,0.0,Purba Bardhaman,Burdwan,"[0101] Sale, Sale Document",Bastu,0
1,AI_ZONE_02,13006,903358.08339,180000.0,1345913.048824,566447.5,65.262535,1383.692466,0.9837,2.870714,0.058204,0.941796,0.0,Paschim Bardhaman,Arrah,"[0101] Sale, Sale Document",Baid,0
2,AI_ZONE_03,49053,399247.783836,101147.0,920600.744134,114114.0,32.090386,318.826933,8.836401,3.218376,0.0,1.0,0.03694,Howrah,Dhulagori,"[0101] Sale, Sale Document",Danga,0
3,AI_ZONE_04,52725,315066.061268,71999.725689,1959930.788658,183595.0,130.185510,956.130502,2.445823,3.966354,0.000019,0.999981,0.001745,Howrah,Mallikbagan,"[0101] Sale, Sale Document",Sali,0
4,AI_ZONE_05,17836,3638.820498,3175.472896,2694894.209015,2118180.0,27.904367,287.985806,13.514353,4.297180,0.968995,0.031005,0.999551,Purba Bardhaman,Fuljhore,"[0101] Sale, Sale Document",Bastu,0
5,AI_ZONE_06,38464,2307.922925,2200.0,3502843.081739,1831500.0,58.008950,1170.547150,1.980371,3.330296,0.007851,0.992149,1.0,Paschim Bardhaman,Bamunara,"[0101] Sale, Sale Document",<NA>,0

In [6]:
artifacts.zone_polygons_gdf[['ai_zone', 'property_count', 'median_value_per_area', 'geometry']].head(7)

,ai_zone,property_count,median_value_per_area,geometry
0,AI_ZONE_01,36358,533333.18764,"MULTIPOLYGON (((534071.387 2602191.018, 534070..."
1,AI_ZONE_02,13006,180000.0,"MULTIPOLYGON (((536153.816 2601925.472, 536161..."
2,AI_ZONE_03,49053,101147.0,"MULTIPOLYGON (((588621.276 2567442.76, 588619...."
3,AI_ZONE_04,52725,71999.725689,"MULTIPOLYGON (((588470.875 2567452.79, 588470...."
4,AI_ZONE_05,17836,3175.472896,"MULTIPOLYGON (((534138.544 2602382.107, 534136..."
5,AI_ZONE_06,38464,2200.0,"MULTIPOLYGON (((535698.643 2602264.006, 535699..."

In [7]:
assignments_path, zones_path, summary_csv_path, summary_json_path = save_zone_outputs(
    artifacts,
    settings.processed_data_dir,
    settings.reports_dir,
)
assignments_path, zones_path, summary_csv_path, summary_json_path

2026-04-30 12:11:25,560 | INFO | pyogrio._io | Created 6 records
2026-04-30 12:11:25,579 | INFO | src.zone_clustering | Saved AI zone assignments to \\wsl.localhost\Ubuntu\home\pulkitv52\valuation_poc\data\processed\ai_zone_assignments.parquet
2026-04-30 12:11:25,580 | INFO | src.zone_clustering | Saved AI zones GeoJSON to \\wsl.localhost\Ubuntu\home\pulkitv52\valuation_poc\data\processed\ai_zones.geojson
2026-04-30 12:11:25,580 | INFO | src.zone_clustering | Saved zone summary CSV to \\wsl.localhost\Ubuntu\home\pulkitv52\valuation_poc\reports\zone_summary.csv
2026-04-30 12:11:25,581 | INFO | src.zone_clustering | Saved zone clustering summary to \\wsl.localhost\Ubuntu\home\pulkitv52\valuation_poc\reports\zone_clustering_summary.json

(WindowsPath('//wsl.localhost/Ubuntu/home/pulkitv52/valuation_poc/data/processed/ai_zone_assignments.parquet'),
 WindowsPath('//wsl.localhost/Ubuntu/home/pulkitv52/valuation_poc/data/processed/ai_zones.geojson'),
 WindowsPath('//wsl.localhost/Ubuntu/home/pulkitv52/valuation_poc/reports/zone_summary.csv'),
 WindowsPath('//wsl.localhost/Ubuntu/home/pulkitv52/valuation_poc/reports/zone_clustering_summary.json'))

In [8]:
summary = json.loads((settings.reports_dir / 'zone_clustering_summary.json').read_text(encoding='utf-8'))
summary

{'input_row_count': 273587,
 'rows_with_geometry': 207442,
 'rows_used_for_clustering': 207442,
 'projected_crs': '{"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json", "type": "ProjectedCRS", "name": "WGS 84 / UTM zone 45N", "base_crs": {"type": "GeographicCRS", "name": "WGS 84", "datum_ensemble": {"name": "World Geodetic System 1984 ensemble", "members": [{"name": "World Geodetic System 1984 (Transit)"}, {"name": "World Geodetic System 1984 (G730)"}, {"name": "World Geodetic System 1984 (G873)"}, {"name": "World Geodetic System 1984 (G1150)"}, {"name": "World Geodetic System 1984 (G1674)"}, {"name": "World Geodetic System 1984 (G1762)"}, {"name": "World Geodetic System 1984 (G2139)"}, {"name": "World Geodetic System 1984 (G2296)"}], "ellipsoid": {"name": "WGS 84", "semi_major_axis": 6378137, "inverse_flattening": 298.257223563}, "accuracy": "2.0", "id": {"authority": "EPSG", "code": 6326}}, "coordinate_system": {"subtype": "ellipsoidal", "axis": [{"name": "Geodetic latitude", "abbreviation": "Lat", "direction": "north", "unit": "degree"}, {"name": "Geodetic longitude", "abbreviation": "Lon", "direction": "east", "unit": "degree"}]}, "id": {"authority": "EPSG", "code": 4326}}, "conversion": {"name": "UTM zone 45N", "method": {"name": "Transverse Mercator", "id": {"authority": "EPSG", "code": 9807}}, "parameters": [{"name": "Latitude of natural origin", "value": 0, "unit": "degree", "id": {"authority": "EPSG", "code": 8801}}, {"name": "Longitude of natural origin", "value": 87, "unit": "degree", "id": {"authority": "EPSG", "code": 8802}}, {"name": "Scale factor at natural origin", "value": 0.9996, "unit": "unity", "id": {"authority": "EPSG", "code": 8805}}, {"name": "False easting", "value": 500000, "unit": "metre", "id": {"authority": "EPSG", "code": 8806}}, {"name": "False northing", "value": 0, "unit": "metre", "id": {"authority": "EPSG", "code": 8807}}]}, "coordinate_system": {"subtype": "Cartesian", "axis": [{"name": "Easting", "abbreviation": "E", "direction": "east", "unit": "metre"}, {"name": "Northing", "abbreviation": "N", "direction": "north", "unit": "metre"}]}, "scope": "Navigation and medium accuracy spatial referencing.", "area": "Between 84\\u00b0E and 90\\u00b0E, northern hemisphere between equator and 84\\u00b0N, onshore and offshore. Bangladesh. Bhutan. China. India. Kazakhstan. Mongolia. Nepal. Russian Federation.", "bbox": {"south_latitude": 0, "west_longitude": 84, "north_latitude": 84, "east_longitude": 90}, "id": {"authority": "EPSG", "code": 32645}}',
 'selected_cluster_count': 6,
 'candidate_cluster_range': [6, 7, 8, 9, 10, 11, 12],
 'silhouette_score': 0.40787896053474826,
 'feature_columns': ['centroid_x',
  'centroid_y',
  'log_value_per_area',
  'log_distance_to_nearest_road',
  'log_distance_to_nearest_facility',
  'facility_count_1km',
  'nearest_road_width',
  'Urban_flag',
  'Rural_flag',
  'flat_flag',
  'nature_land_use_freq',
  'proposed_land_use_freq',
  'nearest_road_category_freq'],
 'output_assignment_rows': 207442,
 'output_zone_rows': 6}